tasks:
  # - name: start
- before: |
    pyenv virtualenv venv
    source activate venv

    pip install --upgrade pip
    pip install --upgrade setuptools
    pip install --upgrade build
    pip install --upgrade twine


  init:  |
    echo "проверка init"
        
  command: python start.py
